release:
  version: "1.1.5"
  updated_date: "2025-04-05"
api_host:
  landingai_personal: "https://api.landing.ai/v1/projects/"
endpoint:
  cortex_analyst_message: "/api/v2/cortex/analyst/message"
  cortex_analyst_feedback: "/api/v2/cortex/analyst/feedback"
  cortex_agent: "/api/v2/cortex/agent:run"
  landingai: "ab945845-aaf9-41f8-9a03-9ab724b2f60c"
snowflake:
  database: "RESUME_AI_DB"
  schema: "IMG_RECG"
  stage: "INSTAGE"
  semantic_analyst_file: "SEMANTIC_FILE/semantic_analyst_file.yaml"
  cortex_search_service: "CS_PRODUCT"

