CREATE OR REPLACE CORTEX SEARCH SERVICE IMG_RECG.CS_PRODUCT
ON PRODUCT_DIMENSION
WAREHOUSE = RESUME_AI_WH
TARGET_LAG = '1 hour'
AS (
  SELECT DISTINCT ITEM AS PRODUCT_DIMENSION FROM IMG_RECG.TRANSACTION
);