/* Create stage */
CREATE STAGE IF NOT EXISTS IMG_RECG.INSTAGE 
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') 
DIRECTORY = ( ENABLE = TRUE);

/* Put file into the stage. */
put file://src/dbscripts/stages/images/snapledger_banner.jpg @IMG_RECG.INSTAGE/BANNER AUTO_COMPRESS=FALSE;

/* Refresh the stage */
ALTER STAGE IMG_RECG.INSTAGE REFRESH;

CREATE TABLE IF NOT EXISTS IMG_RECG.WEBSITE_IMAGES(
    _LOAD_TS TIMESTAMP_NTZ
    , _ID INTEGER AUTOINCREMENT START 1 INCREMENT BY 1 ORDER
    , IMAGE_NAME VARCHAR
    , RELATIVE_PATH VARCHAR
    , SCOPED_FILE_URL VARCHAR
    , FILE_URL VARCHAR
    , SIZE INTEGER
    , DESCRIPTION VARCHAR
    , PRIMARY KEY (_ID));

INSERT OVERWRITE INTO IMG_RECG.WEBSITE_IMAGES(IMAGE_NAME, RELATIVE_PATH, SCOPED_FILE_URL, FILE_URL, SIZE, DESCRIPTION)
    SELECT SUBSTRING(RELATIVE_PATH, POSITION('/', RELATIVE_PATH)+1) AS IMAGE_NAME
        , RELATIVE_PATH
         ,BUILD_SCOPED_FILE_URL(@RAG.INSTAGE, RELATIVE_PATH) AS SCOPED_FILE_URL
        , FILE_URL
        , SIZE
        , SUBSTRING(RELATIVE_PATH, 0, POSITION('/', RELATIVE_PATH)-1) AS DESCRIPTOR
    FROM DIRECTORY(@IMG_RECG.INSTAGE )
    WHERE RELATIVE_PATH ILIKE '%BANNER/%';